title: EVENTECKS SARL
description: Un monde nouveau des solutions nouvelles
baseurl: ""
url: "https://votrenom.github.io"
theme: jekyll-theme-minimal

# Paramètres GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Informations entreprise
company_name: EVENTECKS SARL
email: eventecks@etik.com
phone: +225 0505038403
address: Abidjan-Marcory, Immeuble Plein Ciel, Boulevard Félix Houphouet Boigny
